apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fe-be-app
  namespace: argocd
spec:
  project: default
  source:
# i put olegs cues that what workes (neshon said its ok )
    repoURL: 'https://github.com/olego700/devopshift-welcome.git'
    targetRevision: 'workshop/argo-jenkins-exam'  
    path: exam-code/k8s-manifests  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fe-be-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
